### ISSUE TITLE
2^2 produces 0

### ISSUE THREAD

**Issue by aphex008** [sarthology/caligator#17]
Hei! Not sure if I'm using correct syntax, but when I write 2^2 I expect calculator to do 2 to the power of 2 and produce 4. But result is 0. It appears that calculator does subtraction.

**Comment by SarathSantoshDamaraju** [comment]
Thanks @aphex008. Looking into it.

**Comment by second-division** [comment]
Hey, yeah you're using the false syntax...
2^2 is the bitwise xor-operation and should produce 0, since the two bit-strings are the same.
2**2 is 2 to the power of 2 and produces 4.

**Comment by aphex008** [comment]
Cool. Tnx. 
https://i.imgur.com/bED98PS.png

Is there any documentation on syntax?

**Comment by second-division** [comment]
NP 😄 

I didn't found one, but the source code is quite helpful.
Every operation is defined here:
https://github.com/sarthology/caligator/blob/3f7068488ce42b361288655805999db1d3ef6b10/utils/coreCalc.js#L124-L145

**Comment by aphex008** [comment]
Yep, looks like code is self explanatory and power is the only symbol that has different usage.

**Comment by omBratteng** [comment]
I think, seeing as this is a calculator. That it actually uses ^ for exponent operation.
Like Numi does their operations, https://numi.app/docs/#operations
The bitwise xor-operation uses **xor**, even though in JS, it uses **^**
