### ISSUE TITLE
Line up input and output

### ISSUE THREAD

**Issue by grumpkin** [sarthology/caligator#22]
After more the one calculation the output on the right no longer lines up with the input on the left. After a couple of entries this becomes really jarring and makes the program difficult to use.

Also, if you happen to use all the space on the output side then the output starts getting written off the visible window and you have to scroll down to see it

Feels like both input and output should be aligned and the scroll bar should move both sides in sync

**Comment by RPDeshaies** [comment]
I agree this would make the app even better

e.g. screenshot of misalignment:

![image](https://user-images.githubusercontent.com/6224111/65977064-3d0f5b80-e43f-11e9-89ab-75b9b3ec2057.png)

Another cool thing that could be done would be to add the possibility to create "seperators" using `---` like in markdown to create lines

Or maybe add the possibility to add comments to a line ? 

e.g.
```
CALIGATOR UI

24*365 {Number of weeks in a year} | Number of weeks in a year: 8760

```

**Comment by Nokorbis** [comment]
From what I see in the code, comments begin with **#** :)

**Comment by melanieseltzer** [comment]
Would like to take this issue on :)

**Comment by sarthology** [comment]
@melanieseltzer Thanks for submitting the PR. Extremely sorry for making you guys wait for it so long.
