### ISSUE TITLE
Invalid handling of parentheses

### ISSUE THREAD

**Issue by mauritzn** [sarthology/caligator#23]
Parentheses seem to be handled incorrectly, it seems like they get ignored and the calculation is just run left to right. The odd thing is that with some calculations they work like they are suppose to work, but for most they seem to be ignored.

**Example:**
![image](https://user-images.githubusercontent.com/11979966/65890527-b198ba80-e3ab-11e9-8226-0d151c111cf3.png)

I'm running Kubuntu 19.04 _(KDE)_, and I'm using the deb version.

**Comment by mauritzn** [comment]
After messing around with the source code it seems that the issue is caused by **main.js**. **coreCalc.evalExp**, would give the correct result if the parentheses where still in the argument provided, but **main.js** removes them.

This is why **coreCalc.test.js** shows no errors, since there is nothing wrong with the actually calculations, but rather an issue with the provided expression not getting passed to **coreCalc** correctly.

**Console output:**
![image](https://user-images.githubusercontent.com/11979966/65912103-5203d480-e3d6-11e9-9543-2cd4b3e45ecf.png)

**Comment by martinetmayank** [comment]
In latest build, it's working perfectly fine.
