### ISSUE TITLE
shows wrong result

### ISSUE THREAD

**Issue by ganeshkumar269** [sarthology/caligator#31]
It shows wrong result and doesn't prioritize expression inside parentheses. 

![Screenshot (89)](https://user-images.githubusercontent.com/25707350/65966356-9bf3c580-e47d-11e9-9a9d-73d01c0ff640.png)

**Comment by Nokorbis** [comment]
Same as:
#23 #26 #27

**Comment by Hardik500** [comment]
This issue has been fixed and so it can be closed.
