### ISSUE TITLE
Start writing modules for  Handling Calculations 🧮

### ISSUE THREAD

**Issue by sarthology** [sarthology/caligator#4]
Addition
Subtraction	
Multiplication	
Division	
Exponent	
Bitwise And	
Bitwise Or	
Bitwise Xor

**Comment by Stereoraj** [comment]
I want to pick this up.

**Comment by sarthology** [comment]
Go on !! 💪🏼

**Comment by Stereoraj** [comment]
The same has been reverted at https://github.com/sarthology/caligator/pull/6#issue-304420939.

Looking forward for your input.

**Comment by sarthology** [comment]
On it Raj 😎

**Comment by sarthology** [comment]
Is everything covered here @Stereoraj ?
